---
- name: Install nginx
  apt:
    name: "nginx"
    state: present
  notify: ["restart nginx"]

- name: Add ondrej/php PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: 'present'
    update_cache: "{{ update_cache }}"

- name: Install php on Debian
  apt:
    name: "{{ php_modules }}"
    state: present
  changed_when: yes
  when: php_install|default(False)|bool
