---
- name: Epel activation
  yum:
    name: "epel-release"
    state: present

- name: Remi repo activation
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: Install php7 on Centos
  yum:
    name: "{{ php_packages + php_packages_centos }}"
    state: latest
    enablerepo: "remi-php70"
  changed_when: yes
  notify: ["restart apache"]
