---
# tasks file for apache
- name: Install Apache on Debian.
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: "{{ update_cache }}" 

- name: Enable mod_rewrite
  apache2_module:
    state: present
    name: rewrite 
  changed_when: yes
  notify: [ "restart apache" ]
