---
# tasks file for confpostgresql
- name: Assign privileges
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ project_user }}"
    password: "{{ db_password }}"
    db: postgres
    state: present

- name: Create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ project_name }}"
    owner: "{{ project_user }}"
    state: present
