---
- name: Deny incoming and enable UFW
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: Deny incoming and enable UFW
  ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: Set logging
  ufw:
    logging: 'on'

- name: Allow incoming ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow all access to tcp port 443
  ufw:
    rule: allow
    port: https
    proto: tcp

