---
# if domain_name is set to project_name, it means that Alias template will be used
# else vhost template will be used

- name: Create dir alias.d
  ansible.builtin.file:
    path: "{{ sites_available }}"
    state: directory

- name: Add index.php to list index
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/default
    regexp: "{{ index_config }}"
    replace: "{{ index_config_with_php }}"

- name: Set Url include alias.d
  ansible.builtin.lineinfile:
    dest: /etc/nginx/sites-available/default
    insertafter: "server_name _;"
    line: "\tinclude /etc/nginx/alias.d/*;"

- name: Add apache site configuration files.
  template:
    src: "alias.j2"
    dest: "{{ sites_available }}/{{ project_name }}.conf"
    owner: root
    group: root
    mode: "0744"
  notify: ["restart nginx"]
# - name: Stop apache2 for generating SSL certificat
#   ansible.builtin.service:
#     name: "{{ apache_service }}"
#     state: stop

# - name: Generate SSL certificate
#   shell: "/usr/bin/letsencrypt certonly --standalone --agree-tos -d {{ domain_name }} --email {{ admin_email }} --renew-by-default"
#   notify: [ "restart apache" ]

#- name: Enable the site
#  ansible.builtin.file:
#    src: "{{ sites_available }}/{{ domain_name }}.conf"
#    dest: "{{ sites_enabled }}/{{ domain_name }}.conf"
#    owner: root
#    group: root
#    state: link
