---
- name: Add apache site configuration files.
  template:
    src: "{% if domain_name == project_name %}alias.j2{% else %}vhost.j2{% endif %}"
    dest: "{% if domain_name == project_name %}{{ sites_available }}{% else %}{{ sites_destination }}{% endif %}/{{ domain_name }}.conf"
    owner: nginx
    group: nginx
    mode: '0744'
  notify: ["restart nginx"]

# - name: Stop apache2 for generating SSL certificat
#   ansible.builtin.service:
#     name: "{{ apache_service }}"
#     state: stop

# - name: Generate SSL certificate
#   shell: "/usr/bin/letsencrypt certonly --standalone --agree-tos -d {{ domain_name }} --email {{ admin_email }} --renew-by-default"
#   notify: [ "restart apache" ]

- name: Add firewall rule
  firewalld:
    service: https
    permanent: yes
    state: enabled
  notify: "restart firewalld"

- name: Give permission access workdir
  ansible.builtin.file:
    path: "/home/{{ project_user }}"
    mode: "0755"

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
