---
- name: Include hosts playbook
  import_playbook: host.yml # include the host.yml to ask the target host to which the playbook should be run

- name: Install postgresql
  hosts: dynamically_created_hosts
  roles:
    - role: "postgresql"

