---
- name: Include hosts playbook
  import_playbook: host.yml # include the host.yml to ask the target host to which the playbook should be run

- name: Install apache2 and MySQL
  hosts: dynamically_created_hosts
  roles:
    - role: "apache"
      php_install: yes
    - role: "mysql"
