---
- name: Include hosts playbook
  import_playbook: host.yml # include the host.yml to ask the target host to which the playbook should be run

  roles:
    - role: "confmysql"
    - role: "confapache"
