---
- name: Include hosts playbook
  import_playbook: host.yml # include the host.yml to ask the target host to which the playbook should be run

- name: Prompt user info
  hosts: dynamically_created_hosts

  vars_prompt:
    - name: project_name
      prompt: Enter the project name 
      private: no

    - name: proxied_server_ip
      prompt: Enter the proxied server IP
      private: no

    - name: proxied_port
      prompt: Enter the proxied port
      private: no

    - name: domain_name
      prompt: Enter the domain name
      private: no

    - name: update_cache
      prompt: Enter yes or no to update paquet list cache
      private: no

  pre_tasks:
    - assert:
        that: 
          - project_name | length >= 3
          # - proxied_server_ip is regex("")
          - proxied_port > 0
          # - proxied_port < 65535
          - domain_name is regex("^(no)|([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$") # no or correct domain name structure

  roles:
    - role: "nginx_reverse_proxy"
